FROM python:3.12-slim

WORKDIR /chatbot

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    fastapi \
    uvicorn \
    jsonschema \
    elasticsearch==8.11.0 \
    pydantic \
    sentence-transformers \
    torch

COPY . .

EXPOSE 8000

CMD ["uvicorn", "webapp.backend.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]